version: '3.1'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    privileged: true
    sysctls:
      - net.core.somaxconn=1024
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  kafka:
    image: bitnami/kafka:3.4.1
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  # es因为需要安装ik分词器，所以需要我们自己事先build，指定docker-compose build即可
  es:
    build:
      context: ./docker/es
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
#  kibana:
#    image: kibana:8.11.3
#    container_name: kibana
#    environment:
#      - ELASTICSEARCH_HOSTS=http://es:9200
#    ports:
#      - "5601:5601"
#  backend:
#    build:
#      context: ./docker/app
#    ports:
#      - "8080:8080"
#    environment:
#      # 设置java环境参数，其中upload.server-url和web-url改成容器外部地址，还有，需要邮件请配置SMTP地址
#      - JAVA_OPTS=-Dspring.profiles.active=docker -Dupload.server-url=http://172.16.145.130:8080 -Diassign.web-url=http://172.16.145.130
#  ui:
#    build:
#      context: ./docker/nginx
#    ports:
#      - "80:80"
#    environment:
#      # 后端接口地址，使用容器外部地址
#      - SERVER_URL=http://172.16.145.130:8080
