version: '3.1'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka1:
    image: 'bitnami/kafka'
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.16.145.130:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092

#  kafka2:
#    image: 'bitnami/kafka'
#    restart: always
#    container_name: kafka2
#    ports:
#      - "9093:9092"
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_BROKER_ID=2
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.16.145.130:9093
#      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
#
#  kafka3:
#    image: 'bitnami/kafka'
#    restart: always
#    container_name: kafka3
#    ports:
#      - "9094:9092"
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_BROKER_ID=3
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.16.145.130:9094
#      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092

  es:
    image: elasticsearch:8.8.2
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /tmp/ik:/usr/share/elasticsearch/plugins/ik
  kibana:
    image: kibana:8.8.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - 5601:5601
