spring:
  application:
    name: iassign
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 0
      maximum-pool-size: 5
  jackson:
    time-zone: GMT+8
    date-format: "yyyy-MM-dd HH:mm:ss"
  web:
    resources:
      static-locations:
        - "classpath:/META-INF/resources/"
        - "classpath:/resources/"
        - "classpath:/static/"
        - "classpath:/public/"
        - "file:${upload.path}"
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 512MB